### PR TITLE
Fix topic writer infinite reconnections

### PR DESCRIPTION
**Pull request by art22m**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Hello! 

I've created topic writer with `StartTimeout` 30 seconds and Default or Retry `RetryPolicy`.
Then with ip6tables I've blocked the YDB port to get transport error.
The retries are expected to stop after 30 seconds, but this does not happened. 

The reason why this is happened is `connectionTimeout*resetAttemptEmpiricalCoefficient` overflow. 
If `connectionTimeout` is `time.Duration(math.MaxInt64)` (that is always true, since we do not have options to set `connectionTimeout`), then its multiplication to empirical coefficient (=10) gives negative value (see playground https://goplay.space/#qlIeS6o3PCz). 
As a result, function `CheckResetReconnectionCounters` always returns true. Since `CheckResetReconnectionCounters` gives true, `startOfRetries` in `connectionLoop` loop method always sets to `w.clock.Now()`. Thus, in `CheckRetryMode` there are no chance to get `retriesDuration > settings.StartTimeout` to stop reconnections. As a result, we always get infinite reconnections in `Retry` and `Default` modes.

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Topic writer with `StartTimeout` set to X and Default or Retry `RetryPolicy`.
Topic writer gets any error in Retry mode or retryable error in Default mode. 
After X time topic writer **continue** reconnections. 

Issue Number: N/A

## What is the new behavior?
Topic writer with `StartTimeout` set to X and Default or Retry `RetryPolicy`.
Topic writer gets any error in Retry mode or retryable error in Default mode. 
After X time topic writer **stop** reconnections. 

## Other information

Condition `startOfRetries.IsZero()` is needed to set `startOfRetries` for the first time.
Since with infinite connection duration `CheckResetReconnectionCounters` will return false.

### CODE REVIEW

**Comment by rekby** [comment]
@art22m thanks for your PR, I have been see it and will check soon in details.

Fix [broken test](https://github.com/ydb-platform/ydb-go-sdk/actions/runs/7570744399/job/20717850468?pr=1006#step:4:78) please.

**Comment by rekby** [comment]
Hello.

Thanks for your pr and a lot of work for research and describe the bug.

Function CheckResetReconnectionCounters used for detect when we have established stream and reset counters - for good logging.
The PR solve bug with stop reconnection, but break logging/metric ux.

What you mean about set some reasonable constant for check "connection established" state for case with connection timeout is infinite?

For example - 1 minute. It will be mean:
if last connetion attemp was earler, than 1 minute - then connection was fine established and worked. And reset attemp counter to zero.

**Comment by art22m** [comment]
Hi, thanks for feedback.
> if last connetion attemp was earler, than 1 minute - then connection was fine established and worked. And reset attempt counter to zero.

May be I did not get your point, but should we check last connection was earlier then constant, not later?

I guess you want to compare constant with lastConnectionAttempt variable. 
If the connection was fine stablished, and it worked for some time (`reconnectReason = writer.WaitClose(ctx)`), then lastConnectionAttempt will be larger then our constant and we should zero the attempts.
Contrariwise, if we do not established our connection, this variable always will be small due to this: `prevAttemptTime = now`

**Comment by rekby** [comment]
When reconnect timeout is infinite, then we should check: if duration since last attempt was more then constant.

I want detect a situation:
1. Successfully establish a stream session
2. Successfully receive init message
3. Failed on fist (or one of firsts) message

And count the failure as new attempt for logs and for retry policy.

**Comment by art22m** [comment]
I've made one minute constant, but I guess right constant should be find empirically.

**Comment by rekby** [comment]
@art22m Thanks for the fix:)

**Pull request merged**
